config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  root 'tasks#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :tasks
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :find_task, except: [:index, :create, :new]
    
    def index
        if params[:category].blank?
            @tasks = Task.all.order("created_at DESC")
        else
            @category_id = Category.find_by(name: params[:category]).id
            @tasks = Task.where(category_id: @category_id).order("created_at DESC")
        end
    end
    
    def show
    end
    
    def new
        @task = Task.new
    end

    def create
        @task = Task.new(tasks_params)
        if @task.save
            redirect_to @task
        else
            render 'New'
        end
    end
    
    def edit
    end

    def update
        if @task.update(tasks_params)
            redirect_to @task
        else
            render 'Edit'
        end
        
    end
    
    def destroy
        @task.destroy
        redirect_to root_path
    end
    
    private
    def tasks_params
        params.require(:task).permit(:title, :description, :company, :url, :category_id)
    end

    def find_task
        @task = Task.find(params[:id])
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rabbit</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-brand">
          Rabbit Task
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "All Tasks", root_path %></li>
            <% Category.all.each do |category| %>
              <li><%= link_to category.name, tasks_path(category: category.name) %></li>
            <% end %>
          </ul>
          <%= link_to "New Task", new_task_path, class: "navbar-text navbar-right navbar-link" %>
        </div>
      </div>
    </nav>
    
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= simple_form_for @task do |f| %>
  <%= f.collection_select :category_id, Category.all, :id, :name, { prompt: "Choose a Category" }%>
  <%= f.input :title, label: "Task Title" %>
  <%= f.input :description, label: "Task Description" %>
  <%= f.input :company, label: "Your Company" %>
  <%= f.input :url, label: "Link to Task" %>
  <%= f.button :submit %>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>
 <%= render 'form' %>
 <%= link_to "Back", root_path %>

app/views/tasks/index.html.erb
<% @tasks.each do |task| %>
    <h2><%= link_to task.title, task %></h2>
    <p><%= task.company %></p>
<% end %>

app/views/tasks/new.html.erb
<h1>New Task</h1>
 <%= render 'form' %>
 <%= link_to "Back", root_path %>

app/views/tasks/show.html.erb
<h1>
    <%= @task.title %>
</h1>
<p><%= @task.description %></p>
<p><%= @task.company %></p>
<button class="btn btn-default"><%= link_to "Complete Task", @task.url %></button>
<br>
<br>
<%= link_to 'Home', root_path, class: "btn btn-sm btn-default" %>
<%= link_to 'Edit', edit_task_path(@task), class: "btn btn-sm btn-default" %>
<%= link_to 'Delete', task_path(@task), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-sm btn-danger" %>